<?php
/**
 * The MIT License (MIT)
 * Copyright (c) 2018 Serhii Popov
 * This source file is subject to The MIT License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/MIT
 *
 * @category Popov
 * @package Popov_<package>
 * @author Serhii Popov <popow.serhii@gmail.com>
 * @license https://opensource.org/licenses/MIT The MIT License (MIT)
 */
?>


<?php $this->formRow()->setPartial(null); ?>
<?php foreach ($fieldset as $_subElementOrFieldset) : ?>
    <?php if ($_subElementOrFieldset instanceof \Zend\Form\Element\Hidden) : ?>
        <?= $this->formElement($_subElementOrFieldset); ?>
    <?php else : ?>
        <div class="col-sm-5">
            <?php $type = $_subElementOrFieldset->getAttribute('type'); ?>
            <?php if ('checkbox' === $type) : ?>
                <?= $this->formRow(/*)->setPartial(null)->render(*/$_subElementOrFieldset, null, null, 'form::checkbox'); ?>
                <?//= $this->partial('form::checkbox', ['element' => $element]); ?>
            <?php else : ?>
                <?//= $this->formRow($_subElementOrFieldset, null, null, 'form::element'); ?>
                <?= $this->formElement($_subElementOrFieldset) ?>
            <?php endif; ?>
        </div>
    <?php endif; ?>


<?php endforeach; ?>

<!--
<div class="col-sm-offset-2 col-sm-5">
    <input class="form-control" id="inputEmail3" placeholder="Email" type="email">
</div>
<div class="col-sm-5">
    <div class="checkbox">
        <label>
            <input type="checkbox"> Remember me
        </label>
    </div>
</div>
-->