<?php
/**
 * The MIT License (MIT)
 * Copyright (c) 2018 Serhii Popov
 * This source file is subject to The MIT License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/MIT
 *
 * @category Popov
 * @package Popov_ZfcForm
 * @author Serhii Popov <popow.serhii@gmail.com>
 * @license https://opensource.org/licenses/MIT The MIT License (MIT)
 */
?>
<?php $countVisible = function($fieldset) {
	//$num = count($fieldset);
	$num = 0;
	foreach ($fieldset as $element) {
		if ('hidden' == $element->getAttribute('type')) {
            continue;
		}
        $num++;
	}
	return $num;
} ?>

<?php $this->formRow()->setPartial(null); ?>
<?php $count = $countVisible($fieldset); // це рахує також hidden елементи, тому результат не првильний ?>
<?php //$column = ($count <= 6) ? 2 : 1; ?>
<?php $column = ($count <= 3) ? 4 : (($count <= 6) ? 2 : 1); ?>
<?php foreach ($fieldset as $element) : ?>
    <?php $type = $element->getAttribute('type'); ?>
    <?php if ('hidden' === $type) : ?>
        <?= $this->formElement($element) ?>
    <?php else : ?>
        <?php //$column = $element->getOption('column') ?: $column; ?>
		<?php // Be careful, don't override $column value, such as you lose default value which set before foreach ?>
        <?php // By default all elements have the same size, but this can be changed with $element->setOption('column', $number) ?>
		<div class="col-sm-<?= $element->getOption('column') ?: $column ?>">
            <?php if ('checkbox' === $type) : ?>
                <?= $this->formRow($element, null, null, 'form::checkbox') ?>
                <?//= $this->partial('form::checkbox', ['element' => $element]); ?>
            <?php else : ?>
                <?//= $this->formElement($element) ?>
                <?= $this->formRow($element, null, null, 'form::element'); ?>
            <?php endif; ?>
        </div>
    <?php endif; ?>
<?php endforeach; ?>