<?php
/**
 * The MIT License (MIT)
 * Copyright (c) 2018 Serhii Popov
 * This source file is subject to The MIT License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/MIT
 *
 * @category Popov
 * @package Popov_ZfcForm
 * @author Serhii Popov <popow.serhii@gmail.com>
 * @license https://opensource.org/licenses/MIT The MIT License (MIT)
 */
?>
<?php $this->formRow()->setPartial(null); ?>
<?php $count = count($fieldset); ?>
<?php $column = ($count <= 6) ? 2 : 1; ?>
<?php foreach ($fieldset as $element) : ?>
    <?php $type = $element->getAttribute('type'); ?>
    <?php if ('hidden' === $type) : ?>
        <?= $this->formElement($element) ?>
    <?php else : ?>
        <div class="col-sm-<?= $column ?>">
            <?php if ('checkbox' === $type) : ?>
                <?= $this->formRow($element, null, null, 'form::checkbox') ?>
                <?//= $this->partial('form::checkbox', ['element' => $element]); ?>
            <?php else : ?>
                <?= $this->formElement($element) ?>
                <?//= $this->formRow($_subElementOrFieldset, null, null, 'form::element'); ?>
            <?php endif; ?>
        </div>
    <?php endif; ?>
<?php endforeach; ?>