<?php
/**
 * The MIT License (MIT)
 * Copyright (c) 2018 Serhii Popov
 * This source file is subject to The MIT License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/MIT
 *
 * @category Popov
 * @package Popov_ZfcForm
 * @author Serhii Popov <popow.serhii@gmail.com>
 * @license https://opensource.org/licenses/MIT The MIT License (MIT)
 */
use Zend\Form\Element\Collection as FieldsetCollection;
use Zend\Form\Element\Submit;
?>
<?php $elementOrFieldset = $this->vars('fieldset'); ?>
<?php //$key = $this->vars('key'); ?>
<?php if ($elementOrFieldset->getLabel()) : ?>
<legend>
	<?= $this->formLabel($elementOrFieldset) ?>
	<?php if ($elementOrFieldset instanceof FieldsetCollection && $elementOrFieldset->getOption('allow_add')) : ?>
		<?php $name = str_replace(['[',']'], ['-', ''], $elementOrFieldset->getName()); ?>
		<?php $submit = new Submit('add-' . $name); ?>
		<?php $submit->setAttributes([
            'type' => 'submit',
            'value' => '+',
            //'class' => 'add-answer add-field-group btn btn-success small-btn',
            'class' => 'add-field-group btn btn-success small-btn',
            'data-group-id' => $name,
        ]); ?>
        <?//= $this->formRow($submit, null, null, 'form::element') ?>
        <?= $this->formElement($submit) ?>
    <?php endif; ?>
</legend>
<?php endif; ?>

<?php if ($elementOrFieldset instanceof FieldsetCollection) : ?>
    <?php $name = str_replace(['[',']'], ['-', ''], $elementOrFieldset->getName()); ?>
	<fieldset id="<?= $name ?>">
        <?php foreach ($elementOrFieldset as /*$_key =>*/$fieldset) : ?>
            <?php if ($elementOrFieldset->getOption('allow_add')) : // if we can add, then we can remove it ?>
                <?php //$submit = new Submit('remove-' . $name); ?>
                <?php $submit = new Submit('remove'); ?>
	            <?php $submit->setAttributes([
	                'type' => 'submit',
	                'value' => '-',
	                //'class' => 'add-answer add-field-group btn btn-success small-btn',
	                'class' => 'remove-field-group btn btn-danger small-btn',
	                //'data-group-id' => $name,
	            ]); ?>
		        <?php $fieldset->add($submit); ?>
	        <?php endif; ?>
			<div class="form-group">
                <?= $this->partial('form::element-group', ['fieldset' => $fieldset]) ?>
			</div>
        <?php endforeach; ?>
	</fieldset>
    <?php $this->formRow()->setPartial(null); // zf bug with nested custom template render ?>
    <?= $this->formCollection()->renderTemplate($elementOrFieldset) ?>
<?php else : ?>
    <?php foreach ($elementOrFieldset as $key => $subElementOrFieldset) : ?>
        <?php if ($subElementOrFieldset instanceof \Zend\Form\FieldsetInterface) : ?>
            <?php $name = str_replace(['[',']'], ['-', ''], $elementOrFieldset->getName()); ?>

			<?php // if set "inline" option of fieldset than render inline form ?>
			<?php if ($subElementOrFieldset->getOption('inline')) : ?>
				<div class="form-group">
	                <?= $this->partial('form::element-group', ['fieldset' => $subElementOrFieldset]) ?>
				</div>
			<?php else : ?>
				<fieldset id="<?= $name ?>">
	                <?= $this->partial('form::fieldset', ['fieldset' => $subElementOrFieldset/*, 'key' => $key*/]) ?>
				</fieldset>
			<?php endif; ?>
        <?php else : ?>
            <?= $this->formRow($subElementOrFieldset, null, null, 'form::element') ?>
        <?php endif; ?>
    <?php endforeach; ?>
<?php endif; ?>
